name: Update Jane Street Puzzles

on:
  schedule:
    - cron: '0 12 2 * *'  # Run at 12:00 UTC (8:00 PM Shanghai time) on the 2nd day of every month
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-puzzles:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to repository content
      actions: read    # Allow reading actions
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run puzzle scraper
      run: |
        python main.py
        echo "Data file contents:"
        cat src/data/data.json

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Check for changes
      id: git-check
      run: |
        git add src/data/data.json
        git status
        git diff --cached --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git commit -m "Update Jane Street puzzle data [automated] - $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S CST')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use built-in GITHUB_TOKEN 